# Generated by Django 5.0.7 on 2024-08-01 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('title', 'author')},
        ),
    ]
